#!/usr/bin/python
## Build script
## inst_i denotes ith instruction
## if inst_i==0 than instruction is successful else not
 
import os,time
# Before copying files to notebook we have to start the server and create notebook
print "************************************"
print "Press CTRL-C after server is created"
print "************************************"
time.sleep(5)
inst_0=os.system("./create_sagenb") 
# Change Directory to source - src
inst_1=os.chdir("/root/cse06-07/src")
# Make src
inst_2=os.system("make all")
inst_3=os.system("cd ..")
# Copy files to Sage server folder
inst_4=os.system("cp -r /root/cse06-07/src/lab/* /root/.sage/sage_notebook.sagenb/home/pub/")

if((inst_1 or inst_2 or inst_3 or inst_4)==0):
	print "****************"
	print "Build Successful"
	print "****************"
else:
	print "******************"
	print "Build Unsuccessful"
	print "******************"
