#!/usr/bin/python
## Build script
## inst_i denotes ith instruction
## if inst_i==0 than instruction is successful else not

# Sage Server Stop 
import os 
def stop_server():
	try:
        # if sage notebook server is running, "twist.pid" is created
 	       file = open(os.environ['HOME'] + '/.sage/sage_notebook.sagenb/sagenb.pid', 'r')
	       pid = file.readline()
               file.close()
               print "Stopping sage server..."
               os.system('kill -INT ' + pid)
      	except IOError:
               print "No sage server running." 

stop_server()
