#!/usr/bin/python
## Build script
## inst_i denotes ith instruction
## if inst_i==0 than instruction is successful else not
## 
## Sage Server Start 
## Screen is used to keep server running
import os,time
## Detach sage server after start
print "****************************************"
print "Press CTRL-a + d after server is started" 
print "****************************************"
time.sleep(4)
inst_1=os.system("./start_sage")
if(inst_1==0):
	print "****************"
	print "Start Successful"
	print "****************"
else:
	print "******************"
	print "Start Unsuccessful"
	print "******************"
